import { randomBytes, timingSafeEqual } from "node:crypto";

const TOKEN_BYTES = 32;
const TOKEN_LENGTH_BASE64URL = 43; // 32 bytes in base64url without padding

/**
 * Generate a URL-safe cryptographically random token.
 * Returns a 43-character base64url string (no padding).
 */
export function generateToken(): string {
  return randomBytes(TOKEN_BYTES).toString("base64url");
}

/**
 * Validate that a string has the shape of a token generated by `generateToken()`.
 * Does NOT verify authenticity — only shape.
 */
export function isValidTokenFormat(t: string): boolean {
  return typeof t === "string" && /^[A-Za-z0-9_-]{43}$/.test(t);
}

/**
 * Constant-time equality check for two tokens. Prevents timing attacks when
 * comparing a user-submitted token against a stored token.
 *
 * Returns false if either input is not a valid token format (to avoid leaking
 * information via branching on malformed input).
 */
export function tokensEqual(a: string, b: string): boolean {
  if (!isValidTokenFormat(a) || !isValidTokenFormat(b)) return false;
  const bufA = Buffer.from(a, "utf8");
  const bufB = Buffer.from(b, "utf8");
  if (bufA.length !== bufB.length) return false;
  return timingSafeEqual(bufA, bufB);
}
