import {describe,it,expect} from 'vitest';
import {renderOrderJourney} from '../../web/src/lib/order-journey';
import type {OrderJourney} from '../../src/lib/order-journey.js';
const example:OrderJourney={orders:5,customers:2,complete_mail:1,partial_mail:1,no_mail_acceptance:1,no_delivery_tracking:1,no_item_detail:1,expected_files:8,accepted_files:4,invalid_acceptances:1,later_acceptances:0,email_access_orders:2,email_access_customers:1,older_than_retention:1,retained_since:Date.parse('2026-03-30T12:00:00Z'),retention_days:180};
describe('Lecture prudente du parcours après achat',()=>{
 it('expose clients, lacunes historiques et portée exacte des preuves',()=>{const html=renderOrderJourney(example);for(const text of ['par 2 clients distincts','actuellement payées','Sans trace ne signifie pas sans accès','ne forment pas un taux de conversion','ne prouve pas sa réception','téléchargement complet','180 jours','date incohérente','bundle compte une commande','accès depuis le compte'])expect(html).toContain(text);expect(html).toContain('href="#clients"');expect(html).not.toContain('100 %')});
 it('une absence de réponse ne se transforme pas en absence de ventes',()=>{expect(renderOrderJourney(undefined)).toContain('indisponible');expect(renderOrderJourney(undefined)).not.toContain('0 commande')});
 it('emploie le singulier pour une commande et place les alertes hors des détails',()=>{const html=renderOrderJourney({...example,orders:1,later_acceptances:1});expect(html).toContain('Comprendre la commande et ses preuves');expect(html.indexOf('après ce relevé')).toBeGreaterThan(html.indexOf('</details>'));expect(html.indexOf('date incohérente')).toBeGreaterThan(html.indexOf('</details>'));expect(renderOrderJourney(null)).toContain('indisponible')});
 it('la sélection vide explique ses exclusions',()=>{const html=renderOrderJourney({...example,orders:0,customers:0,complete_mail:0,partial_mail:0,no_mail_acceptance:0,no_delivery_tracking:0,no_item_detail:0,expected_files:0,accepted_files:0,invalid_acceptances:0,later_acceptances:0,email_access_orders:0,email_access_customers:0,older_than_retention:0});expect(html).toContain('Aucune commande');expect(html).toContain('commandes remboursées ou contestées');expect(html).not.toContain('<details')});
});
