import type { LegalDocument, LegalLocale } from "../../../src/legal/terms-2026-09-26";

const doc = (title: string, summary: string, sections: [string, string, string[]][]): LegalDocument => ({
  title, summary, highlights: [], sections: sections.map(([id, title, paragraphs]) => ({ id, title, paragraphs })),
});

export const serviceDocuments: Record<LegalLocale, Record<string, LegalDocument>> = {
  fr: {
    impressum: doc("Mentions légales", "Qui exploite OpenSwissData et comment nous joindre.", [
      ["editeur", "Exploitant et vendeur", ["OpenSwissData est exploité en nom propre par Claude-Alain Martin, Rue de l’Église 23, 1045 Ogens, Suisse. Contact : contact@openswissdata.com. L’activité n’est pas inscrite au registre du commerce. L’exploitant n’est pas assujetti à la TVA suisse."]],
      ["independance", "Un service privé indépendant", ["OpenSwissData n’est ni une autorité ni un registre officiel. Il n’existe aucune affiliation, aucun mandat ni partenariat institutionnel avec l’OFDF/BAZG, l’OFS/BFS, la FINMA, Eurostat, les Nations Unies ou GLEIF. Les noms des organismes désignent uniquement les sources ou sujets concernés."]],
      ["droits", "Droits sur le site et les données", ["Les contenus originaux du site et la compilation commerciale sont distincts des données sources. Les licences et conditions des sources restent applicables ; nous ne revendiquons pas de droits exclusifs sur des données publiques ou sous licence ouverte. Le code éventuellement publié dans un dépôt est soumis à sa propre licence. Les CGV précisent les droits acquis lors d’un achat."]],
      ["signalement", "Question, erreur ou réclamation", ["Écrivez à contact@openswissdata.com en précisant la page ou le fichier, sa version et le problème rencontré. Évitez d’envoyer des données confidentielles inutiles. Les signalements relatifs aux données personnelles sont traités selon la notice de confidentialité. Cette démarche ne limite pas les autres voies de recours."]],
    ]),
    usage: doc("Conditions d’utilisation", "Règles d’accès au site, aux démonstrations et aux outils OpenSwissData.", [
      ["portee", "Portée et documents applicables", ["Ces règles décrivent l’usage du site, de l’espace client et des outils accessibles. Les achats sont régis par les CGV acceptées lors de la commande et leur description produit. La notice de confidentialité explique les traitements de données ; sa consultation ne vaut pas consentement à de la publicité. Une modification de cette page ne modifie pas rétroactivement un achat."]],
      ["compte", "Accès et sécurité", ["Les liens de connexion et de téléchargement sont personnels : gardez-les confidentiels et protégez votre boîte mail. Signalez un accès suspect à contact@openswissdata.com. N’essayez pas de contourner les droits, quotas ou contrôles de sécurité, d’accéder aux données d’autrui ou de perturber le service. Une suspicion d’abus peut conduire à une restriction proportionnée, avec examen humain et possibilité de contacter le support. Les droits et recours issus d’un achat restent régis par les CGV."]],
      ["decision", "Données et décisions", ["Les résultats sont des informations documentaires datées, pas des conseils juridiques, douaniers, financiers ou réglementaires. Avant une déclaration douanière, une décision de conformité ou une décision concernant une personne, vérifiez la source officielle actuelle et le contexte. Une présence ou une absence dans une extraction FINMA ne constitue pas à elle seule une conclusion de conformité ou de risque. Une correspondance de nomenclature peut être partielle ou indicative.", "Les fiches publiques, les fichiers achetés et les index de recherche peuvent avoir des dates différentes, précisées sur leurs supports. Une signature de fichier atteste son intégrité, pas l’exactitude de la source. Les résultats utilisés par une IA doivent être vérifiés par une personne compétente."]],
      ["automates", "API, MCP et automatisations", ["Les outils gratuits restent soumis aux limites techniques affichées. Les nouveaux abonnements MCP payants sont actuellement fermés. Un achat de fichiers ne crée pas d’abonnement MCP. N’envoyez pas de secrets ni de données personnelles inutiles dans une requête. Vous restez responsable de la finalité de vos propres automatisations et de leurs destinataires ; les réponses ne donnent aucune autorisation de prospecter ou de profiler illégalement."]],
      ["disponibilite", "Évolution du service", ["Des maintenances, changements de source et incidents peuvent affecter le service. Les obligations de livraison, de mises à jour et les recours pour un achat sont ceux des CGV et de la description acceptées. Les services tiers reliés par un lien appliquent leurs propres conditions. Le droit suisse s’applique sous réserve des règles impératives et fors obligatoires ; les stipulations contractuelles d’un achat prévalent pour cet achat."]],
    ]),
    provenance: doc("Sources et provenance", "Comprendre d’où viennent les données et ce qu’une vérification de fichier prouve.", [
      ["sources", "Sources distinctes, conditions distinctes", ["TARES provient de l’OFDF/BAZG ; les classifications NOGA de l’OFS/BFS, NACE d’Eurostat et ISIC des Nations Unies ; le registre financier de la FINMA, avec des enrichissements identifiés, notamment GLEIF pour les LEI. Consultez les sources et rapports présents dans chaque archive. L’accès public à une source ne signifie pas que tous ses contenus sont librement redistribuables."]],
      ["tares", "TARES : publication non officielle", ["Les conditions communiquées par l’OFDF/BAZG le 21 avril 2026 imposent notamment la conservation du contenu, la distinction claire avec une publication officielle et l’absence de logo officiel. Les notes explicatives (Erläuterungen) et décisions de classification (Entscheide) sont exclues.", "Dies ist keine offizielle Veröffentlichung. Massgebend sind allein die Veröffentlichungen durch die Bundeskanzlei und das Bundesamt für Zoll- und Grenzsicherheit BAZG.", "L’OFDF/BAZG ne fournit ni garantie, ni assistance, ni interprétation pour cette republication. Une erreur ne peut pas être invoquée contre une taxation, la perception des droits ou une procédure pénale. La source officielle fait foi ; les CGV et la licence jointe précisent les conditions applicables."]],
      ["autres", "FINMA, LEI et classifications", ["La correspondance FINMA du 6 mai 2026 encadre la reprise de ses informations ; elle ne constitue ni une certification du produit ni une autorisation pour toute utilisation imaginable. Les données LEI GLEIF sont proposées sous CC0 1.0, indépendamment de notre travail de compilation. Les droits des autres sources et leurs attributions restent applicables. Les correspondances entre nomenclatures ne sont pas toutes exactes ou exhaustives. STATENT n’est actuellement pas distribué par le service."]],
      ["verification", "Vérifier une archive", ["Conservez le ZIP, sa date et son empreinte SHA-256. Les archives récentes contiennent checksums.sha256 et provenance.json : ce dernier porte les empreintes, les sources et une signature Ed25519. La liste effective des fichiers et les éventuelles limites figurent dans le README et le rapport qualité. Utilisez l’outil de vérification du dépôt et la clé publique publiée par OpenSwissData ; les versions plus anciennes peuvent avoir un contenu différent.", "La signature prouve que le manifeste n’a pas été modifié depuis sa signature par notre clé. L’horodatage RFC 3161, lorsqu’il est présent et valide, ajoute une preuve temporelle. Aucun de ces mécanismes ne garantit l’exactitude métier, l’exhaustivité, la validité juridique des droits ou l’approbation d’une autorité."]],
      ["erreur", "Signaler une erreur ou un droit", ["Adressez le nom du fichier, sa version, la source concernée et une description précise à contact@openswissdata.com. Nous examinons les demandes de rectification ou de retrait et les obligations applicables. Le traitement tient compte des droits des personnes, des sources et des clients ; aucun délai universel de retrait n’est promis."]],
    ]),
    "sdr-policy": doc("Communications et prospection", "À quoi servent nos messages et comment exercer votre choix.", [
      ["service", "Messages nécessaires au service", ["Les confirmations de commande, liens de connexion, livraisons et réponses au support servent à exécuter votre demande ou votre achat. Ils ne constituent pas une inscription à une newsletter. Leur langue suit votre choix connu ; vous pouvez demander un changement."]],
      ["marketing", "Messages commerciaux", ["Un achat, une adresse professionnelle publique ou une présence dans un registre ne valent pas un consentement général à recevoir des campagnes. Toute prospection doit respecter les règles applicables, notamment l’accord préalable lorsqu’il est nécessaire et les conditions strictes de l’exception pour des offres analogues à un client existant. Une communication publicitaire doit permettre d’identifier l’expéditeur et de s’y opposer facilement et gratuitement."]],
      ["choix", "Newsletter et opposition", ["La newsletter est accessible par un abonnement distinct chez Substack, soumis à sa notice. Utilisez son lien de désinscription ou écrivez à contact@openswissdata.com pour vous opposer à nos communications commerciales. Cette opposition ne retire pas vos droits d’achat et n’empêche pas les messages indispensables au compte ou à une commande. Nous ne présentons pas une absence de réponse comme une acceptation."]],
      ["donnees", "Usage des contacts", ["Les échanges de support peuvent être consultés dans notre CRM et traduits pour leur lecture, selon la notice de confidentialité. Aucune autorisation de revendre vos coordonnées ou de les transmettre à un outil de prospection ne résulte d’un achat. Les sources publiques vendues ne doivent pas être utilisées pour une prospection contraire au droit."]],
    ]),
    compliance: doc("Qualité, responsabilités et recours", "Nos engagements vérifiables et leurs limites.", [
      ["engagements", "Ce que nous mettons en œuvre", ["Nous documentons les sources, dates, formats et contrôles des versions distribuées. Les paiements sont traités par Stripe ; les accès aux fichiers sont liés aux droits d’achat. Les CGV décrivent la livraison, les 360 jours de mises à jour incluses et la garantie commerciale de remboursement de 14 jours. Les contrôles et signatures ne constituent pas un audit indépendant ou une certification juridique."]],
      ["limites", "Ce que le service ne garantit pas", ["OpenSwissData n’est pas un conseil réglementaire, un registre officiel ni un organisme de certification. Nous ne déclarons pas une conformité universelle ou une absence de risque. Une fréquence de collecte prévue peut être affectée par un incident ; la date de chaque version permet d’évaluer sa fraîcheur. Vérifiez auprès de la source compétente avant une décision engageante."]],
      ["reclamation", "Un interlocuteur pour les problèmes", ["Pour un fichier manquant, un défaut, une erreur, un droit de source, un problème de sécurité ou une demande sur vos données : contact@openswissdata.com. Précisez la version concernée sans transmettre de secrets ni d’informations personnelles inutiles. Les modalités de remboursement et les réserves légales figurent dans les CGV ; les droits sur les données figurent dans la notice de confidentialité. Aucune démarche amiable ne supprime un recours légal."]],
    ]),
  },
  de: {
    impressum: doc("Impressum", "Betreiber, Verkäufer und Kontakt von OpenSwissData.", [
      ["editeur", "Betreiber und Verkäufer", ["OpenSwissData wird von Claude-Alain Martin im eigenen Namen betrieben: Rue de l’Église 23, 1045 Ogens, Schweiz. Kontakt: contact@openswissdata.com. Die Tätigkeit ist nicht im Handelsregister eingetragen. Der Betreiber ist nicht für die Schweizer Mehrwertsteuer registriert."]],
      ["independance", "Unabhängiger privater Dienst", ["OpenSwissData ist keine Behörde und kein amtliches Register. Es bestehen keine institutionelle Verbindung, Partnerschaft oder Beauftragung durch BAZG, BFS, FINMA, Eurostat, die Vereinten Nationen oder GLEIF. Die Namen bezeichnen ausschliesslich Quellen oder behandelte Themen."]],
      ["droits", "Rechte an Website und Daten", ["Eigene Website-Inhalte und die kommerzielle Zusammenstellung sind von den Quelldaten zu unterscheiden. Lizenzen und Bedingungen der Quellen bleiben anwendbar; wir beanspruchen keine ausschliesslichen Rechte an öffentlichen oder offen lizenzierten Daten. Veröffentlichter Programmcode unterliegt seiner eigenen Lizenz. Die AGB beschreiben die beim Kauf erworbenen Rechte."]],
      ["signalement", "Fragen und Beanstandungen", ["Schreiben Sie an contact@openswissdata.com und nennen Sie Seite oder Datei, Version und Problem. Übermitteln Sie keine unnötigen vertraulichen Daten. Datenschutzanfragen werden nach der Datenschutzerklärung behandelt. Andere Rechtsbehelfe bleiben möglich."]],
    ]),
    usage: doc("Nutzungsbedingungen", "Regeln für Website, Demonstrationen und Werkzeuge von OpenSwissData.", [
      ["portee", "Geltungsbereich", ["Diese Regeln betreffen Website, Kundenbereich und zugängliche Werkzeuge. Für Käufe gelten die bei der Bestellung akzeptierten AGB und die Produktbeschreibung. Die Datenschutzerklärung beschreibt die Datenverarbeitung und ist keine Werbeeinwilligung. Änderungen dieser Seite ändern frühere Käufe nicht rückwirkend."]],
      ["compte", "Zugang und Sicherheit", ["Anmelde- und Downloadlinks sind persönlich: Halten Sie sie geheim und schützen Sie Ihr E-Mail-Postfach. Melden Sie verdächtige Zugriffe an contact@openswissdata.com. Umgehen Sie keine Berechtigungen, Kontingente oder Schutzmassnahmen; greifen Sie nicht auf fremde Daten zu und stören Sie den Dienst nicht. Bei Missbrauchsverdacht sind verhältnismässige Einschränkungen mit menschlicher Prüfung und Kontaktmöglichkeit zum Support möglich. Kaufrechte und Rechtsbehelfe richten sich weiterhin nach den AGB."]],
      ["decision", "Daten und Entscheidungen", ["Ergebnisse sind datierte Sachinformationen, keine Rechts-, Zoll-, Finanz- oder Regulierungsberatung. Prüfen Sie vor Zollanmeldungen, Compliance-Entscheidungen oder Entscheidungen über Personen die aktuelle amtliche Quelle und den Kontext. Ein Treffer oder fehlender Treffer im FINMA-Auszug ist allein kein Compliance- oder Risikoentscheid. Klassifikationszuordnungen können teilweise oder nur indikativ sein.", "Öffentliche Seiten, gekaufte Dateien und Suchindizes können unterschiedliche, jeweils ausgewiesene Datenstände haben. Eine Dateisignatur belegt Integrität, nicht die Richtigkeit der Quelle. Bei KI-Verwendung müssen fachkundige Personen die Ergebnisse überprüfen."]],
      ["automates", "API, MCP und Automatisierung", ["Kostenlose Werkzeuge unterliegen den angegebenen technischen Grenzen. Neue kostenpflichtige MCP-Abonnements sind derzeit geschlossen. Ein Dateikauf eröffnet kein MCP-Abonnement. Übermitteln Sie keine Geheimnisse oder unnötigen Personendaten. Für Zweck und Empfänger Ihrer Automatisierungen bleiben Sie verantwortlich; Ergebnisse erlauben keine rechtswidrige Werbung oder Profilbildung."]],
      ["disponibilite", "Änderungen des Dienstes", ["Wartung, Quellenänderungen und Störungen können den Dienst beeinträchtigen. Liefer-, Aktualisierungs- und Abhilfepflichten eines Kaufs ergeben sich aus den akzeptierten AGB und der Produktbeschreibung. Verlinkte Drittanbieter haben eigene Bedingungen. Schweizer Recht gilt unter Vorbehalt zwingender Regeln und Gerichtsstände; für einen Kauf gehen dessen Vertragsbestimmungen vor."]],
    ]),
    provenance: doc("Quellen und Herkunft", "Datenherkunft und Aussagekraft einer Dateiprüfung.", [
      ["sources", "Unterschiedliche Quellen und Bedingungen", ["TARES stammt vom BAZG, NOGA vom BFS, NACE von Eurostat, ISIC von den Vereinten Nationen und das Finanzregister von der FINMA, mit ausgewiesenen Ergänzungen wie GLEIF-LEI. Beachten Sie die Quellen und Berichte im Archiv. Öffentlich zugängliche Inhalte dürfen nicht automatisch uneingeschränkt weiterverbreitet werden."]],
      ["tares", "TARES: keine amtliche Veröffentlichung", ["Die am 21. April 2026 mitgeteilten BAZG-Bedingungen verlangen insbesondere unveränderte Inhalte, eine klare Unterscheidung von amtlichen Veröffentlichungen und den Verzicht auf amtliche Logos. Erläuterungen und Entscheide sind ausgeschlossen.", "Dies ist keine offizielle Veröffentlichung. Massgebend sind allein die Veröffentlichungen durch die Bundeskanzlei und das Bundesamt für Zoll- und Grenzsicherheit BAZG.", "Das BAZG gewährt für diese Wiederveröffentlichung keine Gewährleistung, Unterstützung oder Auslegungshilfe. Fehler können nicht gegen Veranlagung, Abgabenerhebung oder Strafverfahren geltend gemacht werden. Massgebend ist die amtliche Quelle; AGB und beigefügte Lizenz erläutern die Bedingungen."]],
      ["autres", "FINMA, LEI und Klassifikationen", ["Die FINMA-Korrespondenz vom 6. Mai 2026 betrifft die Übernahme ihrer Informationen; sie ist weder Produktzertifizierung noch Erlaubnis für jede denkbare Nutzung. GLEIF-LEI-Daten stehen unabhängig von unserer Zusammenstellung unter CC0 1.0. Rechte und Quellenangaben anderer Anbieter bleiben anwendbar. Klassifikationszuordnungen sind nicht durchgehend exakt oder vollständig. STATENT wird derzeit nicht bereitgestellt."]],
      ["verification", "Archiv prüfen", ["Bewahren Sie ZIP, Datum und SHA-256-Prüfsumme auf. Neuere Archive enthalten checksums.sha256 und provenance.json mit Prüfsummen, Quellen und Ed25519-Signatur. Tatsächliche Dateien und Einschränkungen stehen in README und Qualitätsbericht. Nutzen Sie das Prüfwerkzeug im Repository und den veröffentlichten öffentlichen Schlüssel. Ältere Versionen können anders aufgebaut sein.", "Die Signatur belegt die Unverändertheit des mit unserem Schlüssel signierten Manifests. Ein vorhandener gültiger RFC-3161-Zeitstempel ergänzt einen Zeitnachweis. Beides garantiert weder fachliche Richtigkeit oder Vollständigkeit noch rechtliche Nutzungsbefugnisse oder behördliche Anerkennung."]],
      ["erreur", "Fehler oder Rechte melden", ["Senden Sie Datei, Version, betroffene Quelle und genaue Beschreibung an contact@openswissdata.com. Berichtigungs- und Entfernungsanfragen werden anhand der Pflichten und Rechte der Personen, Quellen und Kunden geprüft. Eine allgemeingültige Entfernungsfrist wird nicht zugesagt."]],
    ]),
    "sdr-policy": doc("Kommunikation und Werbung", "Zweck unserer Nachrichten und Ihre Wahlmöglichkeiten.", [
      ["service", "Notwendige Servicenachrichten", ["Bestellbestätigungen, Anmeldelinks, Lieferungen und Supportantworten dienen Ihrer Anfrage oder Ihrem Kauf. Sie melden Sie nicht für einen Newsletter an. Die Sprache folgt Ihrer bekannten Präferenz; Sie können eine Änderung verlangen."]],
      ["marketing", "Werbliche Nachrichten", ["Ein Kauf, eine öffentliche Geschäftsadresse oder ein Registereintrag ist keine allgemeine Werbeeinwilligung. Werbung muss die geltenden Regeln erfüllen, insbesondere eine erforderliche vorherige Einwilligung und die engen Voraussetzungen der Ausnahme für ähnliche Angebote an bestehende Kunden. Werbliche Nachrichten müssen den Absender nennen und einen einfachen kostenlosen Widerspruch ermöglichen."]],
      ["choix", "Newsletter und Widerspruch", ["Der Newsletter erfordert eine separate Anmeldung bei Substack und unterliegt dessen Datenschutzhinweisen. Nutzen Sie den Abmeldelink oder schreiben Sie an contact@openswissdata.com, um unserer Werbung zu widersprechen. Kaufrechte und notwendige Konto- oder Bestellnachrichten bleiben bestehen. Schweigen gilt nicht als Zustimmung."]],
      ["donnees", "Kontaktdaten", ["Supportkorrespondenz kann gemäss Datenschutzerklärung im CRM eingesehen und zum Lesen übersetzt werden. Ein Kauf erlaubt weder den Weiterverkauf Ihrer Kontaktdaten noch ihre Übermittlung an ein Werbewerkzeug. Gekaufte öffentliche Quelldaten dürfen nicht für rechtswidrige Werbung genutzt werden."]],
    ]),
    compliance: doc("Qualität, Verantwortung und Abhilfe", "Überprüfbare Zusagen und ihre Grenzen.", [
      ["engagements", "Unsere Massnahmen", ["Wir dokumentieren Quellen, Datenstände, Formate und Prüfungen der gelieferten Versionen. Stripe verarbeitet Zahlungen; Dateizugriffe richten sich nach Kaufrechten. Die AGB beschreiben Lieferung, 360 Tage eingeschlossene Aktualisierungen und die freiwillige 14-Tage-Erstattung. Prüfungen und Signaturen sind weder unabhängiges Audit noch rechtliche Zertifizierung."]],
      ["limites", "Grenzen des Dienstes", ["OpenSwissData ist weder Regulierungsberatung noch amtliches Register oder Zertifizierungsstelle. Wir behaupten keine allgemeine Rechtskonformität oder Risikofreiheit. Geplante Datenerhebungen können durch Störungen verzögert werden; der Versionsstand zeigt die Aktualität. Prüfen Sie vor folgenreichen Entscheidungen die zuständige Quelle."]],
      ["reclamation", "Ansprechpartner", ["Bei fehlenden Dateien, Mängeln, Fehlern, Quellenrechten, Sicherheitsproblemen oder Datenschutzanfragen: contact@openswissdata.com. Nennen Sie die Version, ohne Geheimnisse oder unnötige Personendaten zu übermitteln. Erstattungen und gesetzliche Vorbehalte stehen in den AGB, Datenschutzrechte in der Datenschutzerklärung. Eine gütliche Klärung schliesst Rechtsbehelfe nicht aus."]],
    ]),
  },
  en: {
    impressum: doc("Legal notice", "Who operates OpenSwissData and how to contact us.", [
      ["editeur", "Operator and seller", ["OpenSwissData is operated personally by Claude-Alain Martin, Rue de l’Église 23, 1045 Ogens, Switzerland. Contact: contact@openswissdata.com. The business is not entered in the commercial register. The operator is not registered for Swiss VAT."]],
      ["independance", "An independent private service", ["OpenSwissData is neither a public authority nor an official register. There is no institutional affiliation, partnership or mandate with FOCBS/BAZG, FSO/BFS, FINMA, Eurostat, the United Nations or GLEIF. Their names identify sources or subjects only."]],
      ["droits", "Website and data rights", ["Original website content and the commercial compilation are distinct from source data. Source licences and conditions remain applicable; we claim no exclusive rights in public or openly licensed data. Published code is subject to its own licence. The terms of sale describe the rights acquired with a purchase."]],
      ["signalement", "Questions and complaints", ["Write to contact@openswissdata.com with the page or file, its version and the issue. Avoid unnecessary confidential information. Personal-data requests are handled under the privacy notice. This process does not limit other remedies."]],
    ]),
    usage: doc("Terms of use", "Rules for the OpenSwissData website, demonstrations and tools.", [
      ["portee", "Scope and applicable documents", ["These rules describe use of the website, customer area and available tools. Purchases are governed by the terms accepted at checkout and the product description. The privacy notice explains data processing; reading it does not consent to advertising. Changes to this page do not retrospectively change a purchase."]],
      ["compte", "Access and security", ["Sign-in and download links are personal: keep them confidential and protect your mailbox. Report suspicious access to contact@openswissdata.com. Do not bypass permissions, quotas or security controls, access another person’s data or disrupt the service. Suspected abuse may result in proportionate restrictions, human review and an opportunity to contact support. Purchased rights and remedies remain governed by the terms of sale."]],
      ["decision", "Data and decisions", ["Results are dated reference information, not legal, customs, financial or regulatory advice. Before a customs declaration, compliance decision or decision concerning a person, check the current official source and context. A match or absence in a FINMA extract is not by itself a compliance or risk conclusion. Classification mappings may be partial or indicative.", "Public pages, purchased files and search indexes may have different dates, stated on their respective materials. A file signature establishes integrity, not source accuracy. Outputs used by AI require review by a competent person."]],
      ["automates", "API, MCP and automation", ["Free tools are subject to their stated technical limits. New paid MCP subscriptions are currently closed. Buying files does not create an MCP subscription. Do not submit secrets or unnecessary personal data. You remain responsible for your automations’ purposes and recipients; responses do not authorise unlawful marketing or profiling."]],
      ["disponibilite", "Service changes", ["Maintenance, source changes and incidents can affect the service. Purchase-related delivery, update and remedy obligations are those of the accepted terms and product description. Linked third parties have their own terms. Swiss law applies subject to mandatory rules and jurisdiction; the contractual provisions of a purchase prevail for that purchase."]],
    ]),
    provenance: doc("Sources and provenance", "Where the data comes from and what file verification establishes.", [
      ["sources", "Different sources, different conditions", ["TARES comes from FOCBS/BAZG; NOGA from FSO/BFS, NACE from Eurostat and ISIC from the United Nations; the financial register from FINMA, with identified enrichment including GLEIF LEIs. Refer to the sources and reports in each archive. Public access does not mean all content may be freely redistributed."]],
      ["tares", "TARES: unofficial publication", ["Conditions communicated by FOCBS/BAZG on 21 April 2026 require unchanged content, a clear distinction from official publications and no official logos. Explanatory notes (Erläuterungen) and classification decisions (Entscheide) are excluded.", "Dies ist keine offizielle Veröffentlichung. Massgebend sind allein die Veröffentlichungen durch die Bundeskanzlei und das Bundesamt für Zoll- und Grenzsicherheit BAZG.", "FOCBS/BAZG provides no warranty, support or interpretation for this republication. Errors cannot be invoked against customs assessment, duty collection or criminal proceedings. The official source is authoritative; the terms of sale and included licence specify the applicable conditions."]],
      ["autres", "FINMA, LEI and classifications", ["FINMA correspondence dated 6 May 2026 addresses reuse of its information; it is neither product certification nor permission for every possible use. GLEIF LEI data is provided under CC0 1.0 independently of our compilation. Other sources’ rights and attribution requirements remain applicable. Classification mappings are not all exact or complete. STATENT is not currently distributed by the service."]],
      ["verification", "Verify an archive", ["Keep the ZIP, date and SHA-256 digest. Recent archives contain checksums.sha256 and provenance.json, with file digests, sources and an Ed25519 signature. The actual file list and limitations are described in the README and quality report. Use the repository verification tool and OpenSwissData’s published public key; older versions may differ.", "The signature establishes that the manifest has not changed since being signed by our key. A present and valid RFC 3161 timestamp adds time evidence. Neither guarantees factual accuracy, completeness, legal rights or approval by an authority."]],
      ["erreur", "Report an error or rights issue", ["Send the file, version, source concerned and a precise description to contact@openswissdata.com. Correction and removal requests are reviewed against the relevant duties and the rights of individuals, sources and customers. No universal removal deadline is promised."]],
    ]),
    "sdr-policy": doc("Communications and marketing", "Why we send messages and how to exercise your choice.", [
      ["service", "Necessary service messages", ["Order confirmations, sign-in links, deliveries and support replies fulfil your request or purchase. They do not subscribe you to a newsletter. The language follows your known preference; you can request a change."]],
      ["marketing", "Commercial messages", ["A purchase, public business email address or register entry is not general consent to marketing. Marketing must comply with applicable rules, including prior consent where required and the strict conditions of the existing-customer exception for similar offers. Advertising must identify its sender and provide an easy, free way to object."]],
      ["choix", "Newsletter and objection", ["The newsletter requires a separate subscription at Substack, under its privacy notice. Use the unsubscribe link or write to contact@openswissdata.com to object to our marketing. This does not remove purchased rights or stop necessary account and order messages. Silence is not treated as consent."]],
      ["donnees", "Contact information", ["Support correspondence may be read in our CRM and translated for reading as described in the privacy notice. A purchase does not authorise resale of your contact information or its transfer to a marketing tool. Purchased public-source data must not be used for unlawful marketing."]],
    ]),
    compliance: doc("Quality, responsibilities and remedies", "Verifiable commitments and their limits.", [
      ["engagements", "What we implement", ["We document sources, dates, formats and checks for distributed versions. Stripe handles payments; file access follows purchased rights. The terms of sale describe delivery, 360 days of included updates and the voluntary 14-day refund guarantee. Checks and signatures are neither an independent audit nor legal certification."]],
      ["limites", "Service limitations", ["OpenSwissData is not regulatory advice, an official register or a certification body. We do not claim universal compliance or absence of risk. Incidents can delay planned collection; each version’s date lets you assess freshness. Check the competent source before consequential decisions."]],
      ["reclamation", "A contact for issues", ["For missing files, defects, errors, source rights, security issues or personal-data requests: contact@openswissdata.com. Identify the version without sharing secrets or unnecessary personal information. Refund procedures and legal safeguards are in the terms of sale; data rights are in the privacy notice. Seeking an amicable solution does not remove legal remedies."]],
    ]),
  },
};
