import { terms, type LegalDocument, type LegalLocale } from "../../../src/legal/terms-2026-09-26";

export const legalDate = "2026-09-30";
export const privacy: Record<LegalLocale, LegalDocument> = {
  fr: {
    title: "Confidentialité et données personnelles",
    summary: "Ce que nous traitons pour fournir OpenSwissData, vous assister et protéger le service. Information mise à jour le 30 septembre 2026.",
    highlights: ["Pas de vente des coordonnées clients", "Statistiques internes pseudonymisées", "Traduction des messages sur notre serveur", "Un contact pour exercer vos droits"],
    sections: [
      { id: "responsable", title: "1. Responsable et contact", paragraphs: ["Claude-Alain Martin, exploitant d’OpenSwissData en nom propre, Rue de l’Église 23, 1045 Ogens, Suisse, est responsable des traitements décrits ici. Pour toute demande : contact@openswissdata.com. Cette notice informe sur nos pratiques ; accepter les conditions de vente ne vaut pas consentement à la publicité."] },
      { id: "informations", title: "2. Informations traitées", paragraphs: [
        "Compte et achat : email, identité et entreprise lorsqu’elles sont fournies, adresse de facturation et données de paiement traitées par Stripe, références de transaction, produits, montants, remboursements, contestations, droits d’accès et preuve de la version des conditions acceptées. Nous ne conservons pas le numéro complet de carte ni son code de sécurité.",
        "Relation client : coordonnées professionnelles, langue choisie ou estimée, messages et pièces jointes reçus dans nos boîtes de support, historique des envois, notes de suivi et demandes. La détection de langue est indicative ; les traductions de lecture peuvent comporter des erreurs et l’original est conservé chez le fournisseur de messagerie.",
        "Fonctionnement et sécurité : adresse IP et navigateur nécessaires aux connexions et à la limitation des abus, cookies de connexion, accès aux produits, codes de réponse et durées techniques. Les statistiques internes enregistrent pages ou types d’appels, pays s’il est disponible, domaine référent, catégorie de navigateur et identifiant pseudonymisé changeant chaque jour. Un appel authentifié peut être rattaché au compte. Pseudonymisé ne signifie pas anonyme.",
        "Sources publiques : certaines données diffusées, notamment les registres et avertissements FINMA ou les données LEI/GLEIF, peuvent concerner des personnes physiques ou des indépendants. Elles proviennent des sources citées dans les fichiers et fiches, pas d’une collecte auprès de toutes les personnes concernées. Une mention reflète le contexte et la date de la source ; elle n’est pas une appréciation indépendante de la personne."
      ] },
      { id: "finalites", title: "3. Finalités et fondements", paragraphs: [
        "Nous utilisons ces informations pour préparer et exécuter les achats, fournir l’accès, traiter le support et les réclamations, rapprocher les remboursements, prévenir les abus, vérifier la disponibilité, mesurer l’utilisation et améliorer le service. Les pièces nécessaires sont conservées pour les obligations comptables et la défense de droits.",
        "La loi suisse sur la protection des données encadre ces traitements. Lorsque le RGPD s’applique, les fondements pertinents sont l’exécution du contrat ou de mesures précontractuelles, les obligations légales, et nos intérêts légitimes à assurer un service sûr, à répondre aux demandes et à en mesurer l’usage, sous réserve des droits des personnes. Un consentement est demandé lorsqu’il est requis et peut être retiré pour l’avenir.",
        "Les champs indispensables sont signalés dans les formulaires ; sans email accessible ou paiement confirmé, nous ne pouvons pas fournir l’achat. Le choix de recevoir des publicités n’est pas nécessaire. Nous ne prenons pas, par un modèle de langue, de décision individuelle produisant des effets juridiques sur un client. Les rapprochements financiers et limitations de sécurité peuvent faire l’objet d’un examen humain."
      ] },
      { id: "support", title: "4. Messages, CRM et traduction", paragraphs: [
        "Le bureau de suivi est réservé à l’exploitant autorisé. Il peut réunir les messages adressés au support et les échanges relatifs à OpenSwissData reçus sur la boîte professionnelle personnelle de l’exploitant. Les autres échanges de cette boîte sont exclus du périmètre du CRM. Les originaux restent chez Infomaniak et les envois chez Resend.",
        "La traduction pour la lecture interne s’effectue sur le serveur de l’application avec des modèles installés localement. Le texte n’est pas envoyé à un prestataire de traduction ou de génération de texte. La traduction n’est pas conservée comme un nouveau message et n’est pas envoyée automatiquement à son auteur. Évitez d’envoyer des secrets, données de carte ou informations sensibles sans nécessité."
      ] },
      { id: "prestataires", title: "5. Destinataires et lieux", paragraphs: [
        "L’exploitant et les prestataires nécessaires à leurs missions ont accès aux informations concernées. Stripe traite les paiements (Stripe Payments Europe, Limited, en Irlande, avec des traitements internationaux, notamment aux États-Unis) et peut aussi agir comme responsable distinct pour ses obligations propres. Resend envoie nos mails et en suit la remise : les messages partent de l’infrastructure d’Amazon Web Services en Irlande, mais les données du compte, les journaux et les métadonnées des envois sont conservés aux États-Unis. Infomaniak, en Suisse, héberge les boîtes de courrier, enregistre le nom de domaine, gère ses DNS et redirige l’adresse sans « www ».",
        "Railway héberge l’application et sa base de données dans la région Amsterdam, aux Pays-Bas ; son exploitation et son assistance peuvent impliquer les États-Unis. Cloudflare fournit le stockage R2 des archives distribuées et des sauvegardes chiffrées. Lors d’un téléchargement, votre navigateur se connecte directement à ce stockage, qui reçoit donc votre adresse IP et des informations techniques. Ce stockage n’est pas assorti d’une garantie de résidence dans un pays donné. Les lieux détaillés dépendent de chaque service et de ses sous-traitants.",
        "Plausible (Plausible Insights OÜ, Estonie) mesure l’audience sans cookie, sur une infrastructure située en Allemagne. Sentry (États-Unis) reçoit des erreurs techniques filtrées, conservées dans la région de stockage de l’Union européenne choisie pour notre compte ; les corps de requêtes, cookies, utilisateurs et fils d’activité sont retirés avant envoi. Nous consultons dans Google Search Console des statistiques agrégées sur la présence du site dans la recherche Google ; le site ne charge aucun script Google et ne transmet pas de données de ses visiteurs à Google. Les polices sont servies directement par OpenSwissData, sans connexion du navigateur à Google Fonts. Si vous vous abonnez à notre lettre d’information, Substack (États-Unis, certifié selon le Swiss-U.S. Data Privacy Framework) conserve pour notre compte votre adresse email et des statistiques de lecture ; nous sommes responsables de cette liste, et Substack applique sa propre notice à ses propres finalités. Vous pouvez vous désinscrire à tout moment par le lien présent dans chaque envoi.",
        "Pour les communications hors de Suisse, nous nous appuyons sur un État reconnu par le Conseil fédéral comme offrant une protection adéquate, comme les États de l’Union européenne, sur la certification du destinataire au Swiss-U.S. Data Privacy Framework, reconnu depuis le 15 septembre 2024, ou, à défaut, sur des clauses contractuelles types adaptées au droit suisse. C’est actuellement le cas de Resend, qui n’est pas certifié pour la Suisse. Les accords de traitement, les listes de sous-traitants et la liste officielle des entreprises certifiées sont référencés ci-dessous. Une localisation européenne du serveur ne garantit pas à elle seule l’absence de transfert. Nous pouvons préciser sur demande les destinataires et garanties concernant vos données. Aucune certification globale de conformité n’est revendiquée ici."
      ] },
      { id: "durees", title: "6. Conservation", paragraphs: [
        "Commandes, montants, remboursements et preuve des conditions acceptées (version, langue, empreinte du document) : dix ans à compter de la fin de l’année civile du dernier mouvement de paiement de la commande (achat, remboursement ou contestation), puis effacement automatique, sauf litige ou vérification encore en cours. Les droits d’accès liés à une commande prennent fin avec elle : le compte ne propose alors plus les versions correspondantes, sans effet sur la licence des fichiers déjà téléchargés. Les versions publiées des conditions générales restent archivées.",
        "Notes, fiche, actions et préférence de langue du suivi client : effacées trois ans après votre dernier achat ou le dernier échange enregistré avec vous (note du bureau, action créée ou terminée, clôture d’un incident de livraison, mail de livraison accepté, demande de lien de connexion datant de moins de 30 jours, modification de la fiche). Nous ne gardons pas de trace plus longue des connexions : une connexion plus ancienne ne prolonge pas ce délai. Nous ne conservons pas les courriels dans notre base : un message qui n’a pas été consigné dans une note ne le prolonge pas non plus. Rien n’est effacé tant qu’une action, un incident de livraison ou une vérification de paiement vous concernant reste ouvert. Le suivi d’un compte relié à une application MCP est conservé tant que cette application existe.",
        "Compte client (adresse email, sessions et traces techniques qui en dépendent) : effacé lorsqu’il ne compte plus aucune commande depuis dix ans, une fois ses commandes et son suivi effacés selon les règles ci-dessus, et en l’absence de session en cours. Un compte relié à une application MCP est conservé tant que cette application existe.",
        "Sessions : validité maximale de 30 jours ; liens de connexion : 15 minutes ; liens de livraison : 48 heures. Les éléments expirés sont retirés lors du nettoyage périodique. Les événements statistiques internes et les identifiants techniques des mails de livraison et les traces de liens de téléchargement (compte, produit, version, dates de préparation et d’autorisation, sans le lien secret) sont supprimés au-delà de 180 jours lors de ce nettoyage. Une autorisation de téléchargement ne prouve pas la réception complète ni l’ouverture du fichier.",
        "Copies techniques chiffrées des connecteurs CRM et du rapprochement financier : conservation d’environ 30 jours, avec purge par journée UTC lors du nettoyage périodique (prévu toutes les six heures) et des consultations suivantes, avec des plafonds de volume. Les courriers originaux chez les fournisseurs de messagerie suivent la durée nécessaire à la relation, aux réclamations et aux obligations légales ; cette purge technique ne les efface pas. Les notes du suivi client suivent la règle de trois ans ci-dessus.",
        "Les sauvegardes chiffrées servent à la reprise après incident. Une suppression peut n’y devenir effective qu’à l’expiration de leur cycle de conservation. Chaque effacement automatique est inscrit dans un registre qui ne contient qu’un identifiant interne, une catégorie et une date ; après une restauration, il est réappliqué au démarrage ou, au plus tard, au nettoyage suivant. En cas de restauration, les demandes de suppression encore applicables doivent être réappliquées. Nous examinons les demandes d’effacement pour limiter les données conservées au nécessaire."
      ] },
      { id: "cookies", title: "7. Cookies et mesure d’audience", paragraphs: [
        "Les cookies __Host-osd_session (connexion, trente jours au maximum) et __Host-osd_login (confirmation, cinq minutes au maximum) sont nécessaires à la connexion. Ils sont protégés par les attributs HttpOnly, Secure et SameSite, et limités au site qui les émet. Les liens de paiement conduisent à Stripe, dont les cookies et la notice s’appliquent à sa page. Le site n’utilise pas de cookie publicitaire OpenSwissData ; Plausible fonctionne sans cookie. Cela ne signifie pas qu’aucune donnée technique ne soit traitée. Nos mails ne contiennent pas de pixel de suivi et leurs liens ne passent pas par un service de mesure des clics.",
        "Vous pouvez supprimer les cookies dans votre navigateur ; cela ferme la session. Les mesures internes côté serveur utilisent les données techniques décrites ci-dessus, sans identifiant stable d’un jour à l’autre. Vous pouvez contacter le responsable pour exercer votre opposition lorsque le droit applicable le permet."
      ] },
      { id: "droits", title: "8. Vos droits et signalements", paragraphs: [
        "Selon le droit applicable, vous pouvez demander accès, rectification, effacement, limitation, opposition et remise ou transmission de vos données, sous les conditions prévues par la loi. Écrivez à contact@openswissdata.com en précisant votre demande ; nous pouvons vérifier votre identité de façon proportionnée. Une demande d’accès reçoit en principe une réponse dans les 30 jours, sous réserve des exceptions légales qui vous seront expliquées.",
        "Pour une donnée issue d’un registre public, indiquez la fiche, la source et l’inexactitude alléguée. Nous examinons une correction, une indication de contexte ou un retrait justifié sans altérer silencieusement un document officiel. Vous pouvez saisir le Préposé fédéral à la protection des données et à la transparence (PFPDT), ou l’autorité compétente de votre pays lorsque le RGPD s’applique."
      ] },
      { id: "modifications", title: "9. Modifications de la notice", paragraphs: ["La date de cette page correspond à une révision éditoriale réelle. Une évolution des traitements peut nécessiter sa mise à jour et, lorsque la loi le demande, une information spécifique ou un nouveau consentement. Une nouvelle notice ne vaut pas consentement rétroactif."] }
    ]
  },
  de: {
    title: "Datenschutz und Personendaten",
    summary: "Welche Daten wir für OpenSwissData, Support und Sicherheit bearbeiten. Information vom 30. September 2026.",
    highlights: ["Kein Verkauf von Kundenkontaktdaten", "Pseudonymisierte interne Statistik", "Nachrichtenübersetzung auf unserem Server", "Ein Kontakt für Ihre Rechte"],
    sections: [
      { id: "responsable", title: "1. Verantwortlicher und Kontakt", paragraphs: ["Claude-Alain Martin, Betreiber von OpenSwissData im eigenen Namen, Rue de l’Église 23, 1045 Ogens, Schweiz, ist für die hier beschriebenen Bearbeitungen verantwortlich. Kontakt: contact@openswissdata.com. Diese Erklärung informiert; die Annahme der Verkaufsbedingungen ist keine Werbeeinwilligung."] },
      { id: "informations", title: "2. Bearbeitete Informationen", paragraphs: [
        "Konto und Kauf: E-Mail, angegebene Identität und Firma, von Stripe bearbeitete Rechnungsadresse und Zahlungsdaten, Transaktionsreferenzen, Produkte, Beträge, Erstattungen, Zahlungsstreitigkeiten, Zugriffsrechte und Nachweis der akzeptierten Bedingungen. Wir speichern weder die vollständige Kartennummer noch den Sicherheitscode.",
        "Kundenbeziehung: berufliche Kontaktdaten, gewählte oder geschätzte Sprache, Nachrichten und Anhänge in unseren Supportpostfächern, Versandhistorie, Notizen und Anfragen. Spracherkennung ist eine Schätzung; Übersetzungen können Fehler enthalten. Das Original bleibt beim Mailanbieter.",
        "Betrieb und Sicherheit: IP-Adresse und Browser für Verbindungen und Missbrauchsschutz, Sitzungscookies, Produktzugriffe, Antwortcodes und technische Laufzeiten. Interne Statistiken erfassen Seiten oder Aufruftypen, verfügbares Land, Herkunftsdomäne, Browserkategorie und eine täglich wechselnde pseudonymisierte Kennung. Ein authentifizierter Aufruf kann dem Konto zugeordnet werden. Pseudonymisiert bedeutet nicht anonym.",
        "Öffentliche Quellen: Verbreitete Daten, insbesondere FINMA-Register und Warnungen oder LEI-/GLEIF-Daten, können natürliche Personen und Selbstständige betreffen. Sie stammen aus den in Dateien und Seiten genannten Quellen, nicht aus einer Erhebung bei allen Betroffenen. Ein Eintrag gibt Kontext und Datum der Quelle wieder, keine unabhängige Bewertung der Person."
      ] },
      { id: "finalites", title: "3. Zwecke und Grundlagen", paragraphs: [
        "Wir verwenden die Informationen für Vorbereitung und Durchführung von Käufen, Zugang, Support, Beschwerden, Erstattungsabgleich, Missbrauchsschutz, Verfügbarkeit, Nutzungsstatistik und Verbesserung des Dienstes. Erforderliche Belege dienen Buchführungspflichten und der Rechtsverteidigung.",
        "Es gilt das schweizerische Datenschutzgesetz. Soweit die DSGVO anwendbar ist, sind die relevanten Grundlagen Vertragserfüllung oder vorvertragliche Massnahmen, gesetzliche Pflichten und berechtigte Interessen an einem sicheren Dienst, der Beantwortung von Anfragen und der Nutzungsmessung unter Wahrung der Betroffenenrechte. Wo erforderlich, wird eine für die Zukunft widerrufbare Einwilligung eingeholt.",
        "Pflichtfelder sind gekennzeichnet. Ohne erreichbare E-Mail oder bestätigte Zahlung können wir den Kauf nicht bereitstellen. Werbung ist keine Voraussetzung. Wir treffen mit Sprachmodellen keine individuellen Entscheidungen mit rechtlicher Wirkung für Kunden. Finanzabgleiche und Sicherheitssperren können menschlich überprüft werden."
      ] },
      { id: "support", title: "4. Nachrichten, CRM und Übersetzung", paragraphs: [
        "Der Kundenbereich für die Verwaltung ist nur dem berechtigten Betreiber zugänglich. Er kann Supportnachrichten und OpenSwissData-bezogene Korrespondenz aus dem persönlichen beruflichen Postfach des Betreibers zusammenführen. Andere Nachrichten dieses Postfachs sind vom CRM ausgeschlossen. Originale verbleiben bei Infomaniak, versandte Nachrichten bei Resend.",
        "Leseübersetzungen erfolgen auf dem Anwendungsserver mit lokal installierten Modellen. Texte werden keinem externen Übersetzungs- oder Textgenerierungsanbieter übermittelt. Übersetzungen werden nicht als neue Nachricht gespeichert oder automatisch an den Absender verschickt. Übermitteln Sie keine unnötigen Geheimnisse, Kartendaten oder sensiblen Informationen."
      ] },
      { id: "prestataires", title: "5. Empfänger und Orte", paragraphs: [
        "Der Betreiber und die für ihre Aufgaben erforderlichen Dienstleister haben Zugriff auf die betreffenden Informationen. Stripe verarbeitet Zahlungen (Stripe Payments Europe, Limited, Irland, mit internationaler Bearbeitung, insbesondere in den USA) und kann für eigene Pflichten auch selbst verantwortlich sein. Resend versendet unsere E-Mails und verfolgt deren Zustellung: Die Nachrichten werden über die Infrastruktur von Amazon Web Services in Irland verschickt, Kontodaten, Protokolle und Versandmetadaten werden jedoch in den USA gespeichert. Infomaniak in der Schweiz betreibt die Postfächer, registriert den Domainnamen, verwaltet dessen DNS und leitet die Adresse ohne „www“ weiter.",
        "Railway hostet die Anwendung und ihre Datenbank in der Region Amsterdam, Niederlande; Betrieb und Support können die USA einbeziehen. Cloudflare stellt den R2-Speicher für die ausgelieferten Archive und die verschlüsselten Sicherungen bereit. Beim Herunterladen verbindet sich Ihr Browser direkt mit diesem Speicher, der dadurch Ihre IP-Adresse und technische Angaben erhält. Für diesen Speicher wird kein Speicherort in einem bestimmten Land zugesichert. Einzelheiten hängen vom jeweiligen Dienst und seinen Unterauftragnehmern ab.",
        "Plausible (Plausible Insights OÜ, Estland) misst die Nutzung ohne Cookies auf einer Infrastruktur in Deutschland. Sentry (USA) erhält gefilterte technische Fehlermeldungen, die in der für unser Konto gewählten Speicherregion der Europäischen Union gespeichert werden; Anfrageinhalte, Cookies, Nutzer und Aktivitätsverläufe werden vor dem Versand entfernt. In der Google Search Console sehen wir zusammengefasste Statistiken zur Präsenz der Website in der Google-Suche; die Website lädt kein Google-Skript und übermittelt keine Daten ihrer Besucher an Google. Die Schriftdateien werden direkt von OpenSwissData geladen, ohne Verbindung des Browsers zu Google Fonts. Wenn Sie unseren Newsletter abonnieren, speichert Substack (USA, zertifiziert nach dem Swiss-U.S. Data Privacy Framework) in unserem Auftrag Ihre E-Mail-Adresse und Lesestatistiken; wir sind für diese Liste verantwortlich, und Substack wendet für eigene Zwecke seine eigene Erklärung an. Sie können sich jederzeit über den Link in jeder Ausgabe abmelden.",
        "Für Übermittlungen ausserhalb der Schweiz stützen wir uns auf einen vom Bundesrat als angemessen anerkannten Staat, etwa die Staaten der Europäischen Union, auf die Zertifizierung des Empfängers nach dem Swiss-U.S. Data Privacy Framework, das seit dem 15. September 2024 anerkannt ist, oder andernfalls auf an das Schweizer Recht angepasste Standardvertragsklauseln. Dies gilt derzeit für Resend, das für die Schweiz nicht zertifiziert ist. Auftragsbearbeitungsverträge, Unterauftragnehmerlisten und die offizielle Liste der zertifizierten Unternehmen sind unten verlinkt. Ein europäischer Serverstandort allein schliesst Übermittlungen nicht aus. Auf Anfrage erläutern wir Empfänger und Garantien für Ihre Daten. Eine umfassende Konformitätszertifizierung wird hier nicht behauptet."
      ] },
      { id: "durees", title: "6. Aufbewahrung", paragraphs: [
        "Bestellungen, Beträge, Rückerstattungen und der Nachweis der akzeptierten Bedingungen (Version, Sprache, Prüfsumme des Dokuments): zehn Jahre ab Ende des Kalenderjahres der letzten Zahlungsbewegung der Bestellung (Kauf, Rückerstattung oder Zahlungsanfechtung), danach automatische Löschung, ausser bei einer noch offenen Streitigkeit oder Prüfung. Die an eine Bestellung gebundenen Zugriffsrechte enden mit ihr: Das Konto bietet die entsprechenden Versionen dann nicht mehr an; die Lizenz an bereits heruntergeladenen Dateien bleibt unberührt. Die veröffentlichten Fassungen der Allgemeinen Geschäftsbedingungen bleiben archiviert.",
        "Notizen, Kundenkarte, Aufgaben und Sprachpräferenz der Kundenbetreuung: Löschung drei Jahre nach Ihrem letzten Kauf oder dem letzten bei uns erfassten Austausch mit Ihnen (Notiz, erstellte oder erledigte Aufgabe, Abschluss eines Lieferproblems, angenommene Liefer-E-Mail, Anforderung eines Anmeldelinks in den letzten 30 Tagen, Änderung der Kundenkarte). Anmeldungen bewahren wir nicht länger auf: Eine ältere Anmeldung verlängert diese Frist nicht. E-Mails speichern wir nicht in unserer Datenbank: Eine Nachricht, die nicht in einer Notiz festgehalten wurde, verlängert sie ebenfalls nicht. Solange eine Aufgabe, ein Lieferproblem oder eine Zahlungsprüfung zu Ihnen offen ist, wird nichts gelöscht. Die Kundenbetreuung eines mit einer MCP-Anwendung verbundenen Kontos bleibt bestehen, solange diese Anwendung existiert.",
        "Kundenkonto (E-Mail-Adresse, Sitzungen und davon abhängige technische Spuren): Löschung, wenn seit zehn Jahren keine Bestellung mehr vorliegt, nachdem Bestellungen und Kundenbetreuung nach den obigen Regeln gelöscht wurden, und keine Sitzung aktiv ist. Ein mit einer MCP-Anwendung verbundenes Konto bleibt bestehen, solange diese Anwendung existiert.",
        "Sitzungen: höchstens 30 Tage gültig; Anmeldelinks: 15 Minuten; Lieferlinks: 48 Stunden. Abgelaufene Einträge werden bei der periodischen Bereinigung entfernt. Interne Statistikereignisse sowie technische Kennungen von Liefer-E-Mails und Download-Link-Protokolle (Konto, Produkt, Version, Vorbereitungs- und Freigabezeit, ohne geheimen Link) werden dabei nach 180 Tagen gelöscht. Eine Download-Freigabe beweist weder den vollständigen Empfang noch das Öffnen der Datei.",
        "Verschlüsselte technische Kopien von CRM-Konnektoren und Finanzabgleichen: etwa 30 Tage, Löschung nach UTC-Kalendertag bei der periodischen Bereinigung (alle sechs Stunden vorgesehen) und bei folgenden Abfragen, mit Volumenbegrenzung. Originalmails bei den E-Mail-Anbietern folgen den Erfordernissen der Kundenbeziehung, Beschwerden und gesetzlichen Pflichten; die technische Bereinigung löscht sie nicht. Notizen der Kundenbetreuung folgen der obigen Dreijahresregel.",
        "Verschlüsselte Sicherungen dienen der Wiederherstellung nach Vorfällen. Eine Löschung kann darin erst mit Ablauf des Aufbewahrungszyklus wirksam werden. Jede automatische Löschung wird in einem Register erfasst, das nur eine interne Kennung, eine Kategorie und ein Datum enthält; nach einer Wiederherstellung wird sie beim Start oder spätestens bei der nächsten Bereinigung erneut angewendet. Nach einer Wiederherstellung sind weiterhin gültige Löschbegehren erneut umzusetzen. Wir prüfen Löschbegehren, um die Aufbewahrung auf das Erforderliche zu beschränken."
      ] },
      { id: "cookies", title: "7. Cookies und Statistik", paragraphs: [
        "Die notwendigen Cookies __Host-osd_session (Anmeldung, höchstens dreissig Tage) und __Host-osd_login (Bestätigung, höchstens fünf Minuten) sind durch HttpOnly, Secure und SameSite geschützt und auf die ausstellende Website beschränkt. Zahlungslinks führen zu Stripe, dessen Cookies und Informationen auf seiner Seite gelten. Die Website verwendet kein OpenSwissData-Werbecookie; Plausible funktioniert ohne Cookies. Technische Daten können dennoch bearbeitet werden. Unsere E-Mails enthalten kein Tracking-Pixel, und ihre Links werden nicht über einen Klickmessdienst umgeleitet.",
        "Sie können Cookies im Browser löschen und damit die Sitzung beenden. Serverseitige Messungen verwenden die oben beschriebenen technischen Daten ohne über Tage stabile Kennung. Soweit gesetzlich vorgesehen, können Sie beim Verantwortlichen Widerspruch einlegen."
      ] },
      { id: "droits", title: "8. Rechte und Meldungen", paragraphs: [
        "Je nach anwendbarem Recht können Sie Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch sowie Herausgabe oder Übertragung Ihrer Daten unter den gesetzlichen Voraussetzungen verlangen. Schreiben Sie an contact@openswissdata.com mit Ihrem Anliegen; eine verhältnismässige Identitätsprüfung ist möglich. Auskunft wird grundsätzlich innerhalb von 30 Tagen erteilt, vorbehaltlich erläuterter gesetzlicher Ausnahmen.",
        "Nennen Sie bei Registerdaten den Eintrag, die Quelle und den behaupteten Fehler. Wir prüfen Berichtigung, Kontextangabe oder begründete Entfernung ohne stille Änderung amtlicher Dokumente. Sie können sich an den Eidgenössischen Datenschutz- und Öffentlichkeitsbeauftragten (EDÖB) oder bei anwendbarer DSGVO an die zuständige Behörde Ihres Landes wenden."
      ] },
      { id: "modifications", title: "9. Änderungen", paragraphs: ["Das Datum bezeichnet eine tatsächliche redaktionelle Überarbeitung. Veränderte Bearbeitungen können eine Aktualisierung sowie gesetzlich erforderliche besondere Informationen oder neue Einwilligungen verlangen. Eine neue Erklärung ist keine rückwirkende Einwilligung."] }
    ]
  },
  en: {
    title: "Privacy and personal data",
    summary: "What we process to provide OpenSwissData, assist you and protect the service. Notice updated on 30 September 2026.",
    highlights: ["No sale of customer contact details", "Pseudonymised internal statistics", "Message translation on our server", "One contact to exercise your rights"],
    sections: [
      { id: "responsable", title: "1. Controller and contact", paragraphs: ["Claude-Alain Martin, operating OpenSwissData in his own name, Rue de l’Église 23, 1045 Ogens, Switzerland, is responsible for the processing described here. Contact: contact@openswissdata.com. This notice provides information; accepting sales terms does not constitute marketing consent."] },
      { id: "informations", title: "2. Information processed", paragraphs: [
        "Account and purchase: email, identity and company when provided, billing address and payment details processed by Stripe, transaction references, products, amounts, refunds, disputes, access rights and evidence of the accepted terms version. We do not store full card numbers or security codes.",
        "Customer relationship: business contact details, chosen or estimated language, messages and attachments received in our support mailboxes, sending history, notes and requests. Language detection is indicative; reading translations may contain errors and originals remain with the mail provider.",
        "Operation and security: IP address and browser needed for connections and abuse prevention, session cookies, product access, response codes and technical timings. Internal statistics record pages or call types, country if available, referring domain, browser category and a pseudonymised identifier changing daily. An authenticated call may be linked to the account. Pseudonymised does not mean anonymous.",
        "Public sources: some distributed data, including FINMA registers and warnings or LEI/GLEIF data, may concern individuals or sole traders. They come from sources cited in files and pages, not from direct collection from every person. An entry reflects its source context and date, not an independent assessment of a person."
      ] },
      { id: "finalites", title: "3. Purposes and grounds", paragraphs: [
        "We use information to prepare and fulfil purchases, provide access, handle support and complaints, reconcile refunds, prevent abuse, check availability, measure use and improve the service. Necessary records support accounting obligations and the defence of rights.",
        "Swiss data protection law governs these activities. Where the GDPR applies, relevant grounds are contract performance or pre-contract steps, legal obligations and legitimate interests in secure service, answering requests and measuring use, subject to individuals’ rights. Consent is requested where required and can be withdrawn for the future.",
        "Required fields are indicated. Without an accessible email or confirmed payment, we cannot fulfil a purchase. Receiving advertisements is not required. We do not use a language model to make individual decisions with legal effects on a customer. Financial reconciliation and security restrictions can be reviewed by a person."
      ] },
      { id: "support", title: "4. Messages, CRM and translation", paragraphs: [
        "The management dashboard is restricted to the authorised operator. It may combine support messages with OpenSwissData correspondence from the operator’s personal business mailbox. Other correspondence from that mailbox is excluded from the CRM. Originals remain with Infomaniak and outgoing mail with Resend.",
        "Reading translations run on the application server using locally installed models. Text is not sent to an external translation or text-generation provider. Translations are not stored as new messages or automatically sent to their authors. Avoid unnecessary secrets, card details or sensitive information."
      ] },
      { id: "prestataires", title: "5. Recipients and locations", paragraphs: [
        "The operator and the providers needed for their tasks can access the relevant information. Stripe processes payments (Stripe Payments Europe, Limited, Ireland, with international processing, including in the United States) and may also act as an independent controller for its own obligations. Resend sends our emails and tracks their delivery: messages leave from Amazon Web Services infrastructure in Ireland, but account data, logs and sending metadata are stored in the United States. Infomaniak, in Switzerland, hosts the mailboxes, registers the domain name, manages its DNS and redirects the address without \"www\".",
        "Railway hosts the application and its database in the Amsterdam region, Netherlands; operations and support may involve the United States. Cloudflare provides R2 storage for distributed archives and encrypted backups. When you download a file, your browser connects directly to this storage, which therefore receives your IP address and technical information. This storage comes with no guarantee of residency in a given country. Detailed locations depend on each service and its subprocessors.",
        "Plausible (Plausible Insights OÜ, Estonia) measures audience without cookies on infrastructure located in Germany. Sentry (United States) receives filtered technical errors, stored in the European Union storage region chosen for our account; request bodies, cookies, users and activity trails are removed before sending. In Google Search Console we view aggregated statistics about the site’s presence in Google Search; the site loads no Google script and sends no visitor data to Google. Fonts are served directly by OpenSwissData, without a browser connection to Google Fonts. If you subscribe to our newsletter, Substack (United States, certified under the Swiss-U.S. Data Privacy Framework) stores your email address and reading statistics on our behalf; we are responsible for this list, and Substack applies its own notice to its own purposes. You can unsubscribe at any time using the link in each issue.",
        "For transfers outside Switzerland, we rely on a country recognised by the Federal Council as providing adequate protection, such as the member states of the European Union, on the recipient’s certification under the Swiss-U.S. Data Privacy Framework, recognised since 15 September 2024, or, failing that, on standard contractual clauses adapted to Swiss law. This currently applies to Resend, which is not certified for Switzerland. Processing agreements, subprocessor lists and the official list of certified companies are referenced below. A European server location alone does not rule out transfers. On request we can clarify recipients and safeguards concerning your data. No overall compliance certification is claimed here."
      ] },
      { id: "durees", title: "6. Retention", paragraphs: [
        "Orders, amounts, refunds and evidence of the accepted terms (version, language, document fingerprint): ten years from the end of the calendar year of the order’s last payment event (purchase, refund or dispute), then deleted automatically, unless a dispute or review is still open. Access rights tied to an order end with it: the account then no longer offers the corresponding versions, without affecting the licence to files already downloaded. Published versions of the terms and conditions remain archived.",
        "Notes, customer record, tasks and language preference used for customer care: deleted three years after your last purchase or the last exchange recorded with you (office note, task created or completed, closure of a delivery incident, accepted delivery email, sign-in link request made within the last 30 days, change to the customer record). We keep no record of sign-ins beyond that: an older sign-in does not extend this period. We do not store emails in our database: a message not recorded in a note does not extend it either. Nothing is deleted while a task, delivery incident or payment review concerning you remains open. Customer-care records of an account linked to an MCP application are kept as long as that application exists.",
        "Customer account (email address, sessions and dependent technical records): deleted once it has had no order for ten years, after its orders and customer-care records have been deleted under the rules above, and when no session is active. An account linked to an MCP application is kept as long as that application exists.",
        "Sessions: valid for up to 30 days; sign-in links: 15 minutes; delivery links: 48 hours. Expired entries are removed during periodic cleanup. Internal statistical events as well as delivery-email technical identifiers and download-link records (account, product, version, preparation and authorisation times, without the secret link) are deleted after 180 days during cleanup. Authorising a download does not prove that the file was fully received or opened.",
        "Encrypted technical copies from CRM connectors and financial reconciliation: around 30 days, purged by UTC day during periodic cleanup (scheduled every six hours) and subsequent consultations, with volume caps. Original mail at the email providers is retained as needed for the relationship, complaints and legal duties; technical cleanup does not erase it. Customer-care notes follow the three-year rule above.",
        "Encrypted backups support incident recovery. Deletion may take effect there only when the retention cycle expires. Each automatic deletion is entered in a register holding only an internal identifier, a category and a date; after a restoration, it is reapplied at start-up or, at the latest, at the next cleanup. After a restoration, applicable deletion requests must be reapplied. We review erasure requests to limit retained data to what is needed."
      ] },
      { id: "cookies", title: "7. Cookies and audience measurement", paragraphs: [
        "The necessary cookies __Host-osd_session (sign-in, up to thirty days) and __Host-osd_login (confirmation, up to five minutes) are protected by HttpOnly, Secure and SameSite and restricted to the site that issues them. Payment links lead to Stripe, whose cookies and notice apply on its page. The site uses no OpenSwissData advertising cookie; Plausible works without cookies. This does not mean no technical data are processed. Our emails contain no tracking pixel and their links are not routed through a click-measurement service.",
        "You can remove cookies in your browser, ending the session. Server-side measurement uses the technical data described above without an identifier stable across days. You may contact the controller to object where applicable law provides that right."
      ] },
      { id: "droits", title: "8. Your rights and reports", paragraphs: [
        "Depending on applicable law, you may request access, correction, erasure, restriction, objection and delivery or transfer of your data under statutory conditions. Email contact@openswissdata.com describing your request; proportionate identity verification may be needed. Access requests are normally answered within 30 days, subject to explained statutory exceptions.",
        "For public-register data, identify the entry, source and alleged error. We review correction, context or justified removal without silently altering official documents. You may contact the Swiss Federal Data Protection and Information Commissioner (FDPIC), or your competent national authority where the GDPR applies."
      ] },
      { id: "modifications", title: "9. Notice changes", paragraphs: ["The date reflects an actual editorial revision. Changed processing may require an update and, where legally required, specific information or fresh consent. A new notice is not retrospective consent."] }
    ]
  }
};

export const providerLinks = [
  ["Railway: DPA", "https://railway.com/legal/dpa"],
  ["Railway: subprocessors", "https://trust.railway.com/item/subprocessors"],
  ["Railway: regions", "https://docs.railway.com/deployments/regions"],
  ["Stripe: DPA", "https://stripe.com/legal/dpa"],
  ["Stripe: data transfers addendum", "https://stripe.com/legal/dta"],
  ["Stripe: subprocessors", "https://stripe.com/service-providers/legal"],
  ["Stripe: privacy", "https://stripe.com/privacy"],
  ["Resend: DPA", "https://resend.com/legal/dpa"],
  ["Resend: subprocessors", "https://resend.com/legal/subprocessors"],
  ["Cloudflare: DPA", "https://www.cloudflare.com/cloudflare-customer-dpa/"],
  ["Cloudflare: subprocessors", "https://www.cloudflare.com/gdpr/subprocessors/cloudflare-services/"],
  ["Sentry: DPA", "https://sentry.io/legal/dpa/"],
  ["Sentry: subprocessors", "https://sentry.io/legal/subprocessors/"],
  ["Plausible: DPA", "https://plausible.io/dpa"],
  ["Plausible: data policy", "https://plausible.io/data-policy"],
  ["Infomaniak: DPA (PDF)", "https://www.infomaniak.com/documents/privacy/DPA/Accord_sur_le_traitement_des_donnees_(DPA).pdf"],
  ["Infomaniak: privacy", "https://www.infomaniak.com/fr/cgv/politique-de-confidentialite"],
  ["Google: privacy", "https://policies.google.com/privacy"],
  ["Substack: privacy", "https://substack.com/privacy"], // variante A seulement
  ["Swiss-U.S. Data Privacy Framework: list", "https://www.dataprivacyframework.gov/list"],
  ["PFPDT / EDÖB / FDPIC", "https://www.edoeb.admin.ch/"]
] as const;

export { terms };
