import { Hono } from "hono";
import { serve } from "@hono/node-server";
import { serveStatic } from "@hono/node-server/serve-static";
import { existsSync } from "node:fs";
import { healthRoute } from "./routes/health.js";
import { adminRoute } from "./routes/admin.js";
import { checkoutRoute } from "./routes/checkout.js";
import { stripeWebhookRoute } from "./routes/stripe-webhook.js";
import { authRoute } from "./routes/auth.js";
import { accountRoute } from "./routes/account.js";
import { downloadRoute, publicDownload } from "./routes/download.js";
import { loadEnv } from "./env.js";

export function createApp() {
  const app = new Hono();

  // --- API routes ---
  app.route("/api/health", healthRoute);
  app.route("/api/admin", adminRoute);
  app.route("/api/checkout", checkoutRoute);
  app.route("/api/webhook/stripe", stripeWebhookRoute);
  app.route("/api/auth", authRoute);
  app.route("/api/account", accountRoute);
  app.route("/api", downloadRoute);      // serves /api/account/download-request
  app.route("/api", publicDownload);     // serves /api/download/:token

  // --- Static Astro frontend ---
  // web/dist is relative to repo root (Railway runs node dist/index.js from root)
  const webRoot = "./web/dist";
  if (existsSync(webRoot)) {
    // Serve hashed static assets generated by Astro
    app.use("/_astro/*", serveStatic({ root: webRoot }));
    app.use("/samples/*", serveStatic({ root: webRoot }));
    app.use("/favicon.svg", serveStatic({ root: webRoot, path: "/favicon.svg" }));
    app.use("/favicon.ico", serveStatic({ root: webRoot, path: "/favicon.ico" }));
    app.use("/og-image.png", serveStatic({ root: webRoot, path: "/og-image.png" }));

    // Serve HTML pages — rewrite clean URLs to their index.html file
    app.use(
      "*",
      serveStatic({
        root: webRoot,
        rewriteRequestPath: (path) => {
          if (path === "/") return "/index.html";
          if (path.endsWith("/")) return path + "index.html";
          if (!/\.[a-z0-9]{1,6}$/i.test(path)) return path + "/index.html";
          return path;
        },
      }),
    );
  } else {
    console.warn(
      "[app] web/dist not found — frontend will not be served. Run 'npm run web:build'.",
    );
  }

  return app;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const env = loadEnv();
  const app = createApp();
  serve({ fetch: app.fetch, port: env.PORT });
  console.log(`Listening on :${env.PORT}`);
}
